from pydantic import BaseModel
from typing import Optional
from datetime import datetime

class ArticleBase(BaseModel):
    title: str
    content: str

class ArticleCreate(ArticleBase):
    """Schema for creating a new article"""
    pass  # ✅ Used when creating an article

class ArticleUpdate(BaseModel):
    """Schema for updating an existing article"""
    title: Optional[str] = None
    content: Optional[str] = None

class Article(ArticleBase):
    """Schema for reading an article from the database"""
    id: int  # ✅ Auto-generated by the database
    created_at: datetime  # ✅ Stores article creation timestamp
    updated_at: datetime  # ✅ Stores last update timestamp

    class Config:
        from_orm = True  # ✅ Future-proof Pydantic setting