from pydantic import BaseModel
from typing import Optional


# ✅ Schema for Creating News
class NewsCreate(BaseModel):
    title: str
    content: str


# ✅ Schema for Updating News
class NewsUpdate(BaseModel):
    title: Optional[str] = None
    content: Optional[str] = None


# ✅ Schema for Reading News
class News(NewsCreate):
    id: int  # Auto-generated by the database

    class Config:
        from_attributes = True  # ✅ Correct for Pydantic 2.0
