# 📝 Alembic configuration file

[alembic]
script_location = backend/src/database/migrations

# ✅ Database URL (Make sure this matches your `db_connection.py`)
sqlalchemy.url = postgresql://jpoindexter:dontforgetme@localhost:5432/clarity

[loggers]
keys = root, sqlalchemy, alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s] %(message)s
