# filepath: pytest.ini
[pytest]
; addopts = -v --cov=my_module --cov-report term-missing
; modules = my_module
testpaths = backend/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*