"""Add published_at to news

Revision ID: 4629feec5128
Revises: 4c93e0a5a589
Create Date: 2025-02-22 13:43:35.373026

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4629feec5128"
down_revision: Union[str, None] = "4c93e0a5a589"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_news_id", table_name="news")
    op.drop_table("news")
    op.drop_index("ix_articles_id", table_name="articles")
    op.drop_table("articles")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("summary", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "source", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("url", sa.VARCHAR(length=2083), autoincrement=False, nullable=False),
        sa.Column(
            "published_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="articles_pkey"),
        sa.UniqueConstraint("url", name="articles_url_key"),
    )
    op.create_index("ix_articles_id", "articles", ["id"], unique=False)
    op.create_table(
        "news",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "source", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("url", sa.VARCHAR(length=2083), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="news_pkey"),
        sa.UniqueConstraint("url", name="news_url_key"),
    )
    op.create_index("ix_news_id", "news", ["id"], unique=False)
    # ### end Alembic commands ###
