































export default NewsList;};    );        </div>            ))}                </div>                    <p>{item.description}</p>                    <h2>{item.title}</h2>                <div key={index}>            {news.map((item, index) => (        <div>    return (    }, []);        loadNews();        };            }                console.error("Failed to load news:", error);            } catch (error) {                setNews(newsData);                const newsData = await getNews();            try {        const loadNews = async () => {    useEffect(() => {    const [news, setNews] = useState([]);const NewsList: React.FC = () => {import { getNews } from '../api/news';import React, { useState, useEffect } from 'react';