"""Fixing Alembic migrations

Revision ID: 3987b3f803ff
Revises:
Create Date: 2025-03-14 14:04:46.013652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3987b3f803ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_articles_title', table_name='articles', postgresql_using='gin')
    op.drop_index('idx_articles_tsv', table_name='articles', postgresql_using='gin')
    op.drop_column('articles', 'tsv')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'articles',
        sa.Column(
            'tsv',
            postgresql.TSVECTOR(),
            autoincrement=False,
            nullable=True))
    op.create_index(
        'idx_articles_tsv',
        'articles',
        ['tsv'],
        unique=False,
        postgresql_using='gin')
    op.create_index(
        'idx_articles_title',
        'articles',
        ['title'],
        unique=False,
        postgresql_using='gin')
    # ### end Alembic commands ###
