from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

router = APIRouter(prefix="/summarize", tags=["Summarization"])

class SummarizeRequest(BaseModel):
    text: str

class SummarizeResponse(BaseModel):
    summary: str

@router.post( 
    "/",
    response_model=SummarizeResponse,
    summary="Summarize input text using the AI model",
    description="Takes a block of text and returns a concise summary generated by the AI model.",
    tags=["Summarization"]
)
async def summarize_text(request: SummarizeRequest):
    # Placeholder for actual summarization logic
    if not request.text.strip():
        raise HTTPException(status_code=400, detail="Input text cannot be empty.")
    return {"summary": "This is a summary of the input text."}