"""Add manipulation_risk to summarized_articles

Revision ID: 010fd0980438
Revises: 
Create Date: 2025-04-24 15:24:04.823020
 
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '010fd0980438'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

  
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mock_model_id', table_name='mock_model')
    op.drop_index('ix_mock_model_name', table_name='mock_model')
    op.drop_table('mock_model')
    op.add_column('summarized_articles', sa.Column('manipulation_risk', sa.Float(), nullable=True))
    # Null all tag values to safely cast the column to JSONB
    op.execute("UPDATE summarized_articles SET tags = NULL WHERE tags IS NOT NULL")
    op.execute("ALTER TABLE summarized_articles ALTER COLUMN tags TYPE JSONB USING tags::jsonb")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('summarized_articles', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('summarized_articles', 'manipulation_risk')
    op.create_table('mock_model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='mock_model_pkey')
    )
    op.create_index('ix_mock_model_name', 'mock_model', ['name'], unique=False)
    op.create_index('ix_mock_model_id', 'mock_model', ['id'], unique=False)
    # ### end Alembic commands ###
