"""Fix metadata detection

Revision ID: 67a0c6c6e5e7
Revises: 
Create Date: 2025-02-18 13:25:05.468762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67a0c6c6e5e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('articles', 'summary',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('articles', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('articles', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2083),
               existing_nullable=False)
    op.alter_column('articles', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.drop_column('articles', 'category')
    op.alter_column('news', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('news', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'news', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='unique')
    op.alter_column('news', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('news', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('articles', sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.alter_column('articles', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('articles', 'url',
               existing_type=sa.String(length=2083),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('articles', 'source',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('articles', 'summary',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('articles', 'title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
